trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndPush
    displayName: Build and push to ACR
    jobs:
      - job: Maven
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
      - job: BuildAndPush
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: Docker@2
            inputs:
              command: buildAndPush
              Dockerfile: '**/Dockerfile'
              containerRegistry: 'scacreastus01'
              repository: 'ms-spring-boot'
              addPipelineData: false
              addBaseImageData: false
